# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.category:
            class: LaFolleAgenceBundle\Admin\CategoryAdmin
            arguments: [~, LaFolleAgenceBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Categorie }

    admin.blog_post:
            class: LaFolleAgenceBundle\Admin\PostAdmin
            arguments: [~, LaFolleAgenceBundle\Entity\Post, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Article }


    admin.comment:
            class: LaFolleAgenceBundle\Admin\CommentAdmin
            arguments: [~, LaFolleAgenceBundle\Entity\Comment, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Commentaires }



